source 'https://cdn.cocoapods.org'

platform :ios, '13.0' # Or higher if needed

target 'iosApp' do
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
  pod 'PurchasesHybridCommon', '13.28.0'

  pod 'ComposeApp', :path => '../composeApp'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'shared'
        target.build_configurations.each do |config|
          config.build_settings.delete('ASSETCATALOG_COMPILER_APPICON_NAME')
        end
      end
    end
  end

end